### ISSUE TITLE
Convert to Org mode?

### ISSUE THREAD

**Issue by kaushalmodi** [chrisdone/elisp-guide#7]
Hello,

If you do use Org mode, please read further, else you can close this issue right away :)

If you use Org mode, have you considered converting this document to Org mode?

Few reasons:

- People can clone this repo, and read the document in Org format which has nice subtree navigation and folding features. 
- If you like, you can publish HTML, PDF, even Markdown versions from the same Org file. 
- Even if you don't choose to do the above, GitHub supports basic Org mode rendering. 
- You can publish Emacs-Lisp source blocks plus their output using Org Babel. I.e. you don't need to manually copy/paste the results of Elisp evaluations. 
- Org mode goes very well this this Emacs-related document. 

I can help with this conversion if you are interested.

**Comment by kaushalmodi** [comment]
Very lame of me. I just noticed https://github.com/chrisdone/elisp-guide/blob/master/README.org.

So now the question is, do you manually update both versions? Or do you derive one from another? :)

**Comment by chrisdone** [comment]
I rarely if ever update this guide!
